### ISSUE TITLE
Feature Request: All configuring with names of optional initialization methods

### ISSUE THREAD

**Issue by abierbaum** [alhugone/tslint-strict-null-checks#2]
This rule is great and works very well.  One thing I have found though in that in some of my Angular applications I would like to consider assignments not only in the constructor but also in the ngOnInit method to be considered initialization.

What do you think about making the rule configurable with a list of method names to also consider as possible sources for initialization assignment?  I think this would help people that are using frameworks that use common naming for initialization methods.

**Comment by alhugone** [comment]
I had discussion about it in my team, and I don't think it is good idea
- It would voliate OOP priciple. Object must be in a consistent state after it's construction.
- TypeScript as language should be independet of any framework.
- Now it's a bug that I'm pretty sure it will be fixed*. Then Your code will not compile. Adding feature like this by Lint would extend pure TypeScript language.


[*Issue](https://github.com/Microsoft/TypeScript/issues/8476)
