### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by UselessPickles** [alhugone/tslint-strict-null-checks#4]
tslint: 5.6.0
typescript: 2.5.3
tslint-strict-null-checks: 1.0.0

in tslint.json:
"no-uninitialized": [true, "variables", "properties"]

I get this stack trace:

> TypeError: Cannot read property 'indexOf' of undefined
>     at NoUninitializedPropertiesWalker.isNotInitialized (/Users/jlau/Development/PDS/web-app/node_modules/tslint-strict-null-checks/rules/noUninitializedRule.js:76:100)
>     at NoUninitializedPropertiesWalker.visitPropertyDeclaration (/Users/jlau/Development/PDS/web-app/node_modules/tslint-strict-null-checks/rules/noUninitializedRule.js:71:18)
>     at NoUninitializedPropertiesWalker.SyntaxWalker.visitNode (/Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:467:22)
>     at /Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
>     at visitNodes (/Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:11911:30)
>     at Object.forEachChild (/Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:12162:21)
>     at NoUninitializedPropertiesWalker.SyntaxWalker.walkChildren (/Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
>     at NoUninitializedPropertiesWalker.SyntaxWalker.visitClassExpression (/Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:66:14)
>     at NoUninitializedPropertiesWalker.SyntaxWalker.visitNode (/Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:317:22)
>     at /Users/jlau/Development/PDS/web-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
> 

This error does not seem to prevent various strict null check failures from being found/reported. When there are no issues found, the stack trace is still reported, but does not cause tslint to fail.

I don't know how to debug this to narrow down what source code is being analyzed when this error happens, so I cannot provide a simple reproduction of the issue. I hope you can find something obviously wrong in the code :)

Let me know if there's any other useful  info I could provide.

**Comment by UselessPickles** [comment]
Is there any progress on this issue? Is there anything I can do to help identify the root cause?

**Comment by alhugone** [comment]
Sorry, I could not take care of this before. 
I can't reproduce it ;/

**Comment by UselessPickles** [comment]
I figured it out. You are handling class declarations, but not class expressions. I have a React HOC (higher order component), which is a function that returns a class expression, and the error happens while processing properties within that class expression. 

You need to implement visitClassExpression nearly exactly the same as visitClassDeclaration. You can implement much of it as a single function that accepts a ts.ClassLikeDeclarationBase node (a base class of both ts.ClassDeclaration and ts.ClassExpression), or you could implement it in terms of a node type of ts.ClassLikeDeclaration (which is a union of ts.ClassDeclaration and ts.ClassExpression). 

The only difference between the two visitor implementations is that each needs to call its respective super implementation. A reference to the appropriate super method could be passed as a param to the common implementation.

**Comment by UselessPickles** [comment]
FYI - I temporarily copy/pasted your visitClassDeclaration to implement visitClassExpression identically (but calling the correct super method) in my project, and it fixed the error for me.

**Comment by UselessPickles** [comment]
Example of how I modified the noInitializedRule.js file to work:

```js
    visitClassLikeDeclaration(node, superMethod) {
        if (!super.hasOption(Options.PROPERTIES)) {
            return;
        }
        const _currentClassInitializedProperties = [];
        const constructor = Helpers_1.findConstructor(node.members);
        if (constructor && constructor.body) {
            for (const statement of constructor.body.statements) {
                if (statement.kind !== ts.SyntaxKind.ExpressionStatement) {
                    continue;
                }
                const expressionStatement = statement;
                if (expressionStatement.expression.kind !== ts.SyntaxKind.BinaryExpression) {
                    continue;
                }
                const binaryExpression = expressionStatement.expression;
                if (binaryExpression.left.kind !== ts.SyntaxKind.PropertyAccessExpression) {
                    continue;
                }
                const leftExpression = binaryExpression.left;
                if (leftExpression.expression.kind === ts.SyntaxKind.ThisKeyword) {
                    _currentClassInitializedProperties.push(leftExpression.name.getText());
                }
            }
        }
        this._initializedProperties.push(_currentClassInitializedProperties);
        superMethod.call(this, node);
        this._initializedProperties.pop();
    }
    visitClassDeclaration(node) {
        this.visitClassLikeDeclaration(node, super.visitClassDeclaration);
    }
    visitClassExpression(node) {
        this.visitClassLikeDeclaration(node, super.visitClassExpression);
    }
```

**Comment by UselessPickles** [comment]
@alhugone *bump* - Please review my pull request.
